name: Build and Release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # Electron 构建任务 (Windows/macOS)
  electron-build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Electron
        run: npm run build:electron
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Electron artifacts
        uses: actions/upload-artifact@v4
        with:
          name: electron-${{ matrix.os }}
          path: |
            dist/*.exe
            dist/*.dmg
            dist/*.zip

  # Android 构建任务 (Capacitor)
  android-build:
    runs-on: ubuntu-latest
    needs: electron-build  # 确保先完成Electron构建
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Android SDK
        uses: android-actions/setup-android@v2

      - name: Accept licenses
        run: |
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses
          echo "$ANDROID_HOME/licenses" >> $GITHUB_PATH

      - name: Install Capacitor and dependencies
        run: |
          npm ci
          npm install -g @capacitor/cli
          npx cap sync android  # 同步Web代码到Android项目

      - name: Build Android APK
        run: |
          cd android
          ./gradlew assembleRelease
          ls app/build/outputs/apk/release/

      - name: Sign APK (可选)
        if: contains(github.ref, 'refs/tags/')  # 仅对正式发布签名
        run: |
          echo "${{ secrets.ANDROID_KEYSTORE }}" > keystore.jks
          base64 -d keystore.jks > release.keystore
          cd android
          ./gradlew assembleRelease \
            -Pandroid.injected.signing.store.file=../release.keystore \
            -Pandroid.injected.signing.store.password=${{ secrets.KEYSTORE_PASSWORD }} \
            -Pandroid.injected.signing.key.alias=${{ secrets.KEY_ALIAS }} \
            -Pandroid.injected.signing.key.password=${{ secrets.KEY_PASSWORD }}

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: android-release
          path: |
            android/app/build/outputs/apk/release/*.apk

  # 发布到 GitHub Release (可选)
  release:
    needs: [electron-build, android-build]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts/**/*
          draft: false
