name: Build Electron

on: [push]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.11.1
          
      - name: Install dependencies
        run: |
          npm ci
          npm install electron-builder --save-dev
          
      - name: Build application
        run: npm run build -- --win --x64 --publish never
        
      - name: Verify build output
        run: dir dist\
        
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-installer
          path: dist\*.exe
          if-no-files-found: error
          retention-days: 3
